import animation from './includes/animation.js';
import fixHeight from './includes/fixHeight.js';
import mobileNav from './includes/mobileNav.js';
import scrollToId from './includes/scrollToId.js';
import isDropdown from './includes/isDropdown.js';
import interestingSlider from './includes/interestingSlider.js';
import contactsFormValidation from './includes/contactsFormValidation.js';
import consultFormValidation from './includes/consultFormValidation.js';
import sellFormValidation from './includes/sellFormValidation.js';
import imask from './includes/imask.js';
import initTabs from './includes/initTabs.js';
import petSlider from './includes/petSlider.js';
import photoSwipe from './includes/photoSwipe.js';
import founderSlider from './includes/founderSlider.js';
import newAccordion from './includes/newAccordion.js';
import headerScroll from './includes/headerScroll.js';
import gallerySlider from './includes/gallerySlider.js';
import productsSlider from './includes/productsSlider.js';
import modal from './includes/modal.js';
import '../sass/main.sass';


isDropdown();
fixHeight();
animation();
mobileNav();
contactsFormValidation();
consultFormValidation();
sellFormValidation();
imask();
interestingSlider();
// initTabs();
petSlider();
photoSwipe();
// founderSlider();
newAccordion();
headerScroll();
gallerySlider();
productsSlider();
modal();
scrollToId();
